language: ruby
sudo: required
cache:
  bundler: true
dist: trusty

jdk:
  - oraclejdk8
rvm:
  - 2.4.2
before_script:
  - bundle exec rake db:create
script:
  - bundle exec rake ci
services:
  - redis-server
