language: ruby
sudo: required
cache:
  bundler: true
dist: trusty

jdk:
  - oraclejdk8
rvm:
  - 2.4.1
before_install:
  - gem update --system
  - gem install bundler
  - bundle exec rake db:create
script:
  - bundle exec rake ci
services:
  - redis-server
notifications:
  email: false
